[server]
enableCORS = true
enableXsrfProtection = false
runOnSave = true
maxUploadSize = 200

[browser]
serverAddress = "tools.antematter.io"
gatherUsageStats = false

[theme]
primaryColor = "#F63366"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif" 
